n1 = int(input("Entre com dois numeros inteiros "))
n2 = int(input())
print("Soma = %s" % (n1 + n2))
print("Diferenca = %s" % (n1 - n2))
print("Multiplicacao = %s" % (n1 * n2))
print("Divisao Inteira = %s" % (n1 // n2))
print("Divisao = %s" % (n1 / n2))